
package com.kdgm.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BBDETSISWS", targetNamespace = "http://kaysis.gov.tr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BBDETSISWS {


    /**
     * Verilen Tarih bilgisi ile þu ana kadar Dýþ yazýþma yapabilen kurumlarda yapýlan güncellemeleri getiren metotdur,Detayli Kullanim icin Lutfen Teknik rehbere basvurunuz
     * 
     * @param pGun
     * @param pYil
     * @param pAy
     * @return
     *     returns com.kdgm.webservice.SonuclarOOfKurumBirimWS
     */
    @WebMethod(operationName = "YeniDisYazismaYapanlariGetirWs", action = "http://kaysis.gov.tr/YeniDisYazismaYapanlariGetirWs")
    @WebResult(name = "YeniDisYazismaYapanlariGetirWsResult", targetNamespace = "http://kaysis.gov.tr/")
    @RequestWrapper(localName = "YeniDisYazismaYapanlariGetirWs", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.YeniDisYazismaYapanlariGetirWs")
    @ResponseWrapper(localName = "YeniDisYazismaYapanlariGetirWsResponse", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.YeniDisYazismaYapanlariGetirWsResponse")
    public SonuclarOOfKurumBirimWS yeniDisYazismaYapanlariGetirWs(
        @WebParam(name = "pGun", targetNamespace = "http://kaysis.gov.tr/")
        int pGun,
        @WebParam(name = "pAy", targetNamespace = "http://kaysis.gov.tr/")
        int pAy,
        @WebParam(name = "pYil", targetNamespace = "http://kaysis.gov.tr/")
        int pYil);

    /**
     * Kurumlarin Kullandigi Tum Tip1 Kod tanimlarini Getiren Metot
     * 
     * @return
     *     returns com.kdgm.webservice.SonucResTip1
     */
    @WebMethod(operationName = "TumTip1KodlariGetirWs", action = "http://kaysis.gov.tr/TumTip1KodlariGetirWs")
    @WebResult(name = "TumTip1KodlariGetirWsResult", targetNamespace = "http://kaysis.gov.tr/")
    @RequestWrapper(localName = "TumTip1KodlariGetirWs", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.TumTip1KodlariGetirWs")
    @ResponseWrapper(localName = "TumTip1KodlariGetirWsResponse", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.TumTip1KodlariGetirWsResponse")
    public SonucResTip1 tumTip1KodlariGetirWs();

    /**
     * Kurumlarin Kullandigi Tum Tip2 Kod tanimlarini Getiren Metot
     * 
     * @return
     *     returns com.kdgm.webservice.SonucResTip2
     */
    @WebMethod(operationName = "TumTip2KodlariGetirWs", action = "http://kaysis.gov.tr/TumTip2KodlariGetirWs")
    @WebResult(name = "TumTip2KodlariGetirWsResult", targetNamespace = "http://kaysis.gov.tr/")
    @RequestWrapper(localName = "TumTip2KodlariGetirWs", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.TumTip2KodlariGetirWs")
    @ResponseWrapper(localName = "TumTip2KodlariGetirWsResponse", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.TumTip2KodlariGetirWsResponse")
    public SonucResTip2 tumTip2KodlariGetirWs();

    /**
     * Kurumlarin Kullandigi Tum Yerkodlarin  tanimlarini Getiren Metot
     * 
     * @return
     *     returns com.kdgm.webservice.SonucResYerKod
     */
    @WebMethod(operationName = "TumYerKodlariGetirWs", action = "http://kaysis.gov.tr/TumYerKodlariGetirWs")
    @WebResult(name = "TumYerKodlariGetirWsResult", targetNamespace = "http://kaysis.gov.tr/")
    @RequestWrapper(localName = "TumYerKodlariGetirWs", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.TumYerKodlariGetirWs")
    @ResponseWrapper(localName = "TumYerKodlariGetirWsResponse", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.TumYerKodlariGetirWsResponse")
    public SonucResYerKod tumYerKodlariGetirWs();

    /**
     * Verilen Kurumun Iletisim Bilgisini Getiren Metot
     * 
     * @param detsisId
     * @return
     *     returns com.kdgm.webservice.SonucIletisimBilgileri
     */
    @WebMethod(operationName = "KurumBirimIletisimBilgileriGetirWs", action = "http://kaysis.gov.tr/KurumBirimIletisimBilgileriGetirWs")
    @WebResult(name = "KurumBirimIletisimBilgileriGetirWsResult", targetNamespace = "http://kaysis.gov.tr/")
    @RequestWrapper(localName = "KurumBirimIletisimBilgileriGetirWs", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.KurumBirimIletisimBilgileriGetirWs")
    @ResponseWrapper(localName = "KurumBirimIletisimBilgileriGetirWsResponse", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.KurumBirimIletisimBilgileriGetirWsResponse")
    public SonucIletisimBilgileri kurumBirimIletisimBilgileriGetirWs(
        @WebParam(name = "detsisId", targetNamespace = "http://kaysis.gov.tr/")
        int detsisId);

    /**
     * Ana kurumlarin Iletisim Bilgilerini Getiren Metot
     * 
     * @return
     *     returns com.kdgm.webservice.SonucIletisimBilgileri
     */
    @WebMethod(operationName = "AnakurumIletisimBilgileriWs", action = "http://kaysis.gov.tr/AnakurumIletisimBilgileriWs")
    @WebResult(name = "AnakurumIletisimBilgileriWsResult", targetNamespace = "http://kaysis.gov.tr/")
    @RequestWrapper(localName = "AnakurumIletisimBilgileriWs", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.AnakurumIletisimBilgileriWs")
    @ResponseWrapper(localName = "AnakurumIletisimBilgileriWsResponse", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.AnakurumIletisimBilgileriWsResponse")
    public SonucIletisimBilgileri anakurumIletisimBilgileriWs();

    /**
     * Ana Kurumlarin Butce Turleri.
     * 
     * @return
     *     returns com.kdgm.webservice.SonuclarOOfAnaKurumlarButceTurleri
     */
    @WebMethod(operationName = "AnaKurumlarButceTurleriGetirWs", action = "http://kaysis.gov.tr/AnaKurumlarButceTurleriGetirWs")
    @WebResult(name = "AnaKurumlarButceTurleriGetirWsResult", targetNamespace = "http://kaysis.gov.tr/")
    @RequestWrapper(localName = "AnaKurumlarButceTurleriGetirWs", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.AnaKurumlarButceTurleriGetirWs")
    @ResponseWrapper(localName = "AnaKurumlarButceTurleriGetirWsResponse", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.AnaKurumlarButceTurleriGetirWsResponse")
    public SonuclarOOfAnaKurumlarButceTurleri anaKurumlarButceTurleriGetirWs();

    /**
     * Anakurumkodu ile Standart Dosya Planý Kodlarýný getiren metotdur.
     * 
     * @param idariKimlikKodu
     * @return
     *     returns com.kdgm.webservice.SonuclarOOfKodlarWsObj
     */
    @WebMethod(operationName = "KurumSDPKodlariGetirWs", action = "http://kaysis.gov.tr/KurumSDPKodlariGetirWs")
    @WebResult(name = "KurumSDPKodlariGetirWsResult", targetNamespace = "http://kaysis.gov.tr/")
    @RequestWrapper(localName = "KurumSDPKodlariGetirWs", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.KurumSDPKodlariGetirWs")
    @ResponseWrapper(localName = "KurumSDPKodlariGetirWsResponse", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.KurumSDPKodlariGetirWsResponse")
    public SonuclarOOfKodlarWsObj kurumSDPKodlariGetirWs(
        @WebParam(name = "IdariKimlikKodu", targetNamespace = "http://kaysis.gov.tr/")
        int idariKimlikKodu);

    /**
     * DETSISNo ile Kurum/Birim bilgileri sorgulayan metotdur.
     * 
     * @param detsisNo
     * @return
     *     returns com.kdgm.webservice.SonucO
     */
    @WebMethod(operationName = "DETSISNoKurumBirimWs", action = "http://kaysis.gov.tr/DETSISNoKurumBirimWs")
    @WebResult(name = "DETSISNoKurumBirimWsResult", targetNamespace = "http://kaysis.gov.tr/")
    @RequestWrapper(localName = "DETSISNoKurumBirimWs", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.DETSISNoKurumBirimWs")
    @ResponseWrapper(localName = "DETSISNoKurumBirimWsResponse", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.DETSISNoKurumBirimWsResponse")
    public SonucO detsisNoKurumBirimWs(
        @WebParam(name = "DETSISNo", targetNamespace = "http://kaysis.gov.tr/")
        int detsisNo);

    /**
     * Gönderilen DETSISNo paremetresine baðlý alt birimleri getiren metotdur.
     * 
     * @return
     *     returns com.kdgm.webservice.SonuclarOOfKurumBirimWS
     */
    @WebMethod(operationName = "KendiTumBirimleriGetirWs", action = "http://kaysis.gov.tr/KendiTumBirimleriGetirWs")
    @WebResult(name = "KendiTumBirimleriGetirWsResult", targetNamespace = "http://kaysis.gov.tr/")
    @RequestWrapper(localName = "KendiTumBirimleriGetirWs", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.KendiTumBirimleriGetirWs")
    @ResponseWrapper(localName = "KendiTumBirimleriGetirWsResponse", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.KendiTumBirimleriGetirWsResponse")
    public SonuclarOOfKurumBirimWS kendiTumBirimleriGetirWs();

    /**
     * Verilen DETSISNona baðlý Ana Kurumuna kadar olan bütün üst birimleri getiren metotdur.
     * 
     * @param detsisNo
     * @return
     *     returns com.kdgm.webservice.SonuclarOOfKurumBirimWS
     */
    @WebMethod(operationName = "HiyerarsiGetirKurumBirimWs", action = "http://kaysis.gov.tr/HiyerarsiGetirKurumBirimWs")
    @WebResult(name = "HiyerarsiGetirKurumBirimWsResult", targetNamespace = "http://kaysis.gov.tr/")
    @RequestWrapper(localName = "HiyerarsiGetirKurumBirimWs", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.HiyerarsiGetirKurumBirimWs")
    @ResponseWrapper(localName = "HiyerarsiGetirKurumBirimWsResponse", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.HiyerarsiGetirKurumBirimWsResponse")
    public SonuclarOOfKurumBirimWS hiyerarsiGetirKurumBirimWs(
        @WebParam(name = "DETSISNo", targetNamespace = "http://kaysis.gov.tr/")
        int detsisNo);

    /**
     * Verilen AnaDETSISNo ya baðlý verilen Ada uygun Kurum/Birim listesi dönen metotdur.
     * 
     * @param ad
     * @param anaKurumIdareKimlikKodu
     * @return
     *     returns com.kdgm.webservice.SonuclarOOfKurumBirimWS
     */
    @WebMethod(operationName = "AdaGoreKurumBirimSorgulaWs", action = "http://kaysis.gov.tr/AdaGoreKurumBirimSorgulaWs")
    @WebResult(name = "AdaGoreKurumBirimSorgulaWsResult", targetNamespace = "http://kaysis.gov.tr/")
    @RequestWrapper(localName = "AdaGoreKurumBirimSorgulaWs", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.AdaGoreKurumBirimSorgulaWs")
    @ResponseWrapper(localName = "AdaGoreKurumBirimSorgulaWsResponse", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.AdaGoreKurumBirimSorgulaWsResponse")
    public SonuclarOOfKurumBirimWS adaGoreKurumBirimSorgulaWs(
        @WebParam(name = "ad", targetNamespace = "http://kaysis.gov.tr/")
        String ad,
        @WebParam(name = "anaKurumIdareKimlikKodu", targetNamespace = "http://kaysis.gov.tr/")
        int anaKurumIdareKimlikKodu);

    /**
     * Ana kurumlarýn listesini dönen metotdur.
     * 
     * @return
     *     returns com.kdgm.webservice.SonuclarOOfKurumBirimWS
     */
    @WebMethod(operationName = "AnaKurumlariGetirKurumBirimWs", action = "http://kaysis.gov.tr/AnaKurumlariGetirKurumBirimWs")
    @WebResult(name = "AnaKurumlariGetirKurumBirimWsResult", targetNamespace = "http://kaysis.gov.tr/")
    @RequestWrapper(localName = "AnaKurumlariGetirKurumBirimWs", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.AnaKurumlariGetirKurumBirimWs")
    @ResponseWrapper(localName = "AnaKurumlariGetirKurumBirimWsResponse", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.AnaKurumlariGetirKurumBirimWsResponse")
    public SonuclarOOfKurumBirimWS anaKurumlariGetirKurumBirimWs();

    /**
     * Yer Kodu, Tip 1 ve Tip 2 ye göre kurum listesi dönen metotdur.
     * 
     * @param statuID
     * @param kategoriID
     * @param ilKodu
     * @param yerKodu
     * @return
     *     returns com.kdgm.webservice.SonuclarOOfKurumBirimWS
     */
    @WebMethod(operationName = "DetayBilgilereGoreSorgulaKurumBirimWs", action = "http://kaysis.gov.tr/DetayBilgilereGoreSorgulaKurumBirimWs")
    @WebResult(name = "DetayBilgilereGoreSorgulaKurumBirimWsResult", targetNamespace = "http://kaysis.gov.tr/")
    @RequestWrapper(localName = "DetayBilgilereGoreSorgulaKurumBirimWs", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.DetayBilgilereGoreSorgulaKurumBirimWs")
    @ResponseWrapper(localName = "DetayBilgilereGoreSorgulaKurumBirimWsResponse", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.DetayBilgilereGoreSorgulaKurumBirimWsResponse")
    public SonuclarOOfKurumBirimWS detayBilgilereGoreSorgulaKurumBirimWs(
        @WebParam(name = "yerKodu", targetNamespace = "http://kaysis.gov.tr/")
        int yerKodu,
        @WebParam(name = "kategoriID", targetNamespace = "http://kaysis.gov.tr/")
        int kategoriID,
        @WebParam(name = "statuID", targetNamespace = "http://kaysis.gov.tr/")
        int statuID,
        @WebParam(name = "IlKodu", targetNamespace = "http://kaysis.gov.tr/")
        int ilKodu);

    /**
     * KEP Adresi kontrolününün yapýldýðý metotdur.
     * 
     * @param kepAdresi
     * @return
     *     returns com.kdgm.webservice.SonucOOfKepBilgileriWs
     */
    @WebMethod(operationName = "KEPAdresiKontrolEt", action = "http://kaysis.gov.tr/KEPAdresiKontrolEt")
    @WebResult(name = "KEPAdresiKontrolEtResult", targetNamespace = "http://kaysis.gov.tr/")
    @RequestWrapper(localName = "KEPAdresiKontrolEt", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.KEPAdresiKontrolEt")
    @ResponseWrapper(localName = "KEPAdresiKontrolEtResponse", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.KEPAdresiKontrolEtResponse")
    public SonucOOfKepBilgileriWs kepAdresiKontrolEt(
        @WebParam(name = "KepAdresi", targetNamespace = "http://kaysis.gov.tr/")
        String kepAdresi);

    /**
     * Ýstenen Kurumlarýn KEP Adres listesini veren metotdur.
     * 
     * @param detsisIDs
     * @return
     *     returns com.kdgm.webservice.SonuclarOOfKepBilgileriWs
     */
    @WebMethod(operationName = "KEPAdresleriniGetir", action = "http://kaysis.gov.tr/KEPAdresleriniGetir")
    @WebResult(name = "KEPAdresleriniGetirResult", targetNamespace = "http://kaysis.gov.tr/")
    @RequestWrapper(localName = "KEPAdresleriniGetir", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.KEPAdresleriniGetir")
    @ResponseWrapper(localName = "KEPAdresleriniGetirResponse", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.KEPAdresleriniGetirResponse")
    public SonuclarOOfKepBilgileriWs kepAdresleriniGetir(
        @WebParam(name = "DetsisIDs", targetNamespace = "http://kaysis.gov.tr/")
        ArrayOfInt detsisIDs);

    /**
     * Aktif olan tüm KEP Adreslerinin listesini veren metotdur.
     * 
     * @return
     *     returns com.kdgm.webservice.SonuclarOOfKepBilgileriWs
     */
    @WebMethod(operationName = "AktifKEPAdresleriniGetir", action = "http://kaysis.gov.tr/AktifKEPAdresleriniGetir")
    @WebResult(name = "AktifKEPAdresleriniGetirResult", targetNamespace = "http://kaysis.gov.tr/")
    @RequestWrapper(localName = "AktifKEPAdresleriniGetir", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.AktifKEPAdresleriniGetir")
    @ResponseWrapper(localName = "AktifKEPAdresleriniGetirResponse", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.AktifKEPAdresleriniGetirResponse")
    public SonuclarOOfKepBilgileriWs aktifKEPAdresleriniGetir();

    /**
     * 
     * @param gonderenDetsisID
     * @param muhatapDetsisIDs
     * @return
     *     returns com.kdgm.webservice.SonucOOfeYazismaPaketi
     */
    @WebMethod(action = "http://kaysis.gov.tr/eYazismaPaketi")
    @WebResult(name = "eYazismaPaketiResult", targetNamespace = "http://kaysis.gov.tr/")
    @RequestWrapper(localName = "eYazismaPaketi", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.EYazismaPaketi")
    @ResponseWrapper(localName = "eYazismaPaketiResponse", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.EYazismaPaketiResponse")
    public SonucOOfeYazismaPaketi eYazismaPaketi(
        @WebParam(name = "gonderenDetsisID", targetNamespace = "http://kaysis.gov.tr/")
        int gonderenDetsisID,
        @WebParam(name = "muhatapDetsisIDs", targetNamespace = "http://kaysis.gov.tr/")
        ArrayOfInt muhatapDetsisIDs);

    /**
     * 
     * @param kutukNoList
     * @return
     *     returns com.kdgm.webservice.SonuclarOOfDevletTeskilatiKutukWs
     */
    @WebMethod(operationName = "KutukNodanDetsisNoGetir", action = "http://kaysis.gov.tr/KutukNodanDetsisNoGetir")
    @WebResult(name = "KutukNodanDetsisNoGetirResult", targetNamespace = "http://kaysis.gov.tr/")
    @RequestWrapper(localName = "KutukNodanDetsisNoGetir", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.KutukNodanDetsisNoGetir")
    @ResponseWrapper(localName = "KutukNodanDetsisNoGetirResponse", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.KutukNodanDetsisNoGetirResponse")
    public SonuclarOOfDevletTeskilatiKutukWs kutukNodanDetsisNoGetir(
        @WebParam(name = "kutukNoList", targetNamespace = "http://kaysis.gov.tr/")
        ArrayOfString kutukNoList);

    /**
     * 
     * @return
     *     returns com.kdgm.webservice.SonuclarOOfDetsisKullanici
     */
    @WebMethod(operationName = "DetsisIslemYetkilisiBilgileriWs", action = "http://kaysis.gov.tr/DetsisIslemYetkilisiBilgileriWs")
    @WebResult(name = "DetsisIslemYetkilisiBilgileriWsResult", targetNamespace = "http://kaysis.gov.tr/")
    @RequestWrapper(localName = "DetsisIslemYetkilisiBilgileriWs", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.DetsisIslemYetkilisiBilgileriWs")
    @ResponseWrapper(localName = "DetsisIslemYetkilisiBilgileriWsResponse", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.DetsisIslemYetkilisiBilgileriWsResponse")
    public SonuclarOOfDetsisKullanici detsisIslemYetkilisiBilgileriWs();

    /**
     * 
     * @param arananKurum
     * @return
     *     returns com.kdgm.webservice.SonuclarOOfKurumBirimWS
     */
    @WebMethod(operationName = "AltKurulusBirimleriListele", action = "http://kaysis.gov.tr/AltKurulusBirimleriListele")
    @WebResult(name = "AltKurulusBirimleriListeleResult", targetNamespace = "http://kaysis.gov.tr/")
    @RequestWrapper(localName = "AltKurulusBirimleriListele", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.AltKurulusBirimleriListele")
    @ResponseWrapper(localName = "AltKurulusBirimleriListeleResponse", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.AltKurulusBirimleriListeleResponse")
    public SonuclarOOfKurumBirimWS altKurulusBirimleriListele(
        @WebParam(name = "arananKurum", targetNamespace = "http://kaysis.gov.tr/")
        int arananKurum);

    /**
     * 
     * @param tcKimlikNo
     * @return
     *     returns com.kdgm.webservice.SonuclarOOfIyemYoneticiObj
     */
    @WebMethod(operationName = "IYEMTCdenGorevListesiGetirWs", action = "http://kaysis.gov.tr/IYEMTCdenGorevListesiGetirWs")
    @WebResult(name = "IYEMTCdenGorevListesiGetirWsResult", targetNamespace = "http://kaysis.gov.tr/")
    @RequestWrapper(localName = "IYEMTCdenGorevListesiGetirWs", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.IYEMTCdenGorevListesiGetirWs")
    @ResponseWrapper(localName = "IYEMTCdenGorevListesiGetirWsResponse", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.IYEMTCdenGorevListesiGetirWsResponse")
    public SonuclarOOfIyemYoneticiObj iyemtCdenGorevListesiGetirWs(
        @WebParam(name = "TCKimlikNo", targetNamespace = "http://kaysis.gov.tr/")
        String tcKimlikNo);

    /**
     * 
     * @param yoneticiID
     * @return
     *     returns com.kdgm.webservice.SonuclarOOfIyemYoneticiObj
     */
    @WebMethod(operationName = "IYEMYoneticiIDdenGorevListesiGetirWs", action = "http://kaysis.gov.tr/IYEMYoneticiIDdenGorevListesiGetirWs")
    @WebResult(name = "IYEMYoneticiIDdenGorevListesiGetirWsResult", targetNamespace = "http://kaysis.gov.tr/")
    @RequestWrapper(localName = "IYEMYoneticiIDdenGorevListesiGetirWs", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.IYEMYoneticiIDdenGorevListesiGetirWs")
    @ResponseWrapper(localName = "IYEMYoneticiIDdenGorevListesiGetirWsResponse", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.IYEMYoneticiIDdenGorevListesiGetirWsResponse")
    public SonuclarOOfIyemYoneticiObj iyemYoneticiIDdenGorevListesiGetirWs(
        @WebParam(name = "YoneticiID", targetNamespace = "http://kaysis.gov.tr/")
        int yoneticiID);

    /**
     * 
     * @param kurumID
     * @param tarih
     * @return
     *     returns com.kdgm.webservice.SonuclarOOfIyemYoneticiObj
     */
    @WebMethod(operationName = "IYEMKurumYoneticisiGetirWs", action = "http://kaysis.gov.tr/IYEMKurumYoneticisiGetirWs")
    @WebResult(name = "IYEMKurumYoneticisiGetirWsResult", targetNamespace = "http://kaysis.gov.tr/")
    @RequestWrapper(localName = "IYEMKurumYoneticisiGetirWs", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.IYEMKurumYoneticisiGetirWs")
    @ResponseWrapper(localName = "IYEMKurumYoneticisiGetirWsResponse", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.IYEMKurumYoneticisiGetirWsResponse")
    public SonuclarOOfIyemYoneticiObj iyemKurumYoneticisiGetirWs(
        @WebParam(name = "KurumID", targetNamespace = "http://kaysis.gov.tr/")
        int kurumID,
        @WebParam(name = "Tarih", targetNamespace = "http://kaysis.gov.tr/")
        XMLGregorianCalendar tarih);

    /**
     * 
     * @param kurumID
     * @return
     *     returns com.kdgm.webservice.SonuclarOOfIyemYoneticiObj
     */
    @WebMethod(operationName = "IYEMTumYoneticileriGetirWs", action = "http://kaysis.gov.tr/IYEMTumYoneticileriGetirWs")
    @WebResult(name = "IYEMTumYoneticileriGetirWsResult", targetNamespace = "http://kaysis.gov.tr/")
    @RequestWrapper(localName = "IYEMTumYoneticileriGetirWs", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.IYEMTumYoneticileriGetirWs")
    @ResponseWrapper(localName = "IYEMTumYoneticileriGetirWsResponse", targetNamespace = "http://kaysis.gov.tr/", className = "com.kdgm.webservice.IYEMTumYoneticileriGetirWsResponse")
    public SonuclarOOfIyemYoneticiObj iyemTumYoneticileriGetirWs(
        @WebParam(name = "KurumID", targetNamespace = "http://kaysis.gov.tr/")
        int kurumID);

}
