
package com.kdgm.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DETSISServis", targetNamespace = "http://kaysis.gov.tr/", wsdlLocation = "file:/C:/Users/ramazan.cesur/Desktop/flash/DETSISServis.wsdl")
public class DETSISServis
    extends Service
{

    private final static URL DETSISSERVIS_WSDL_LOCATION;
    private final static WebServiceException DETSISSERVIS_EXCEPTION;
    private final static QName DETSISSERVIS_QNAME = new QName("http://kaysis.gov.tr/", "DETSISServis");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/ramazan.cesur/Desktop/flash/DETSISServis.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DETSISSERVIS_WSDL_LOCATION = url;
        DETSISSERVIS_EXCEPTION = e;
    }

    public DETSISServis() {
        super(__getWsdlLocation(), DETSISSERVIS_QNAME);
    }

    public DETSISServis(WebServiceFeature... features) {
        super(__getWsdlLocation(), DETSISSERVIS_QNAME, features);
    }

    public DETSISServis(URL wsdlLocation) {
        super(wsdlLocation, DETSISSERVIS_QNAME);
    }

    public DETSISServis(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DETSISSERVIS_QNAME, features);
    }

    public DETSISServis(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DETSISServis(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BBDETSISWS
     */
    @WebEndpoint(name = "BBDETSISWS")
    public BBDETSISWS getBBDETSISWS() {
        return super.getPort(new QName("http://kaysis.gov.tr/", "BBDETSISWS"), BBDETSISWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BBDETSISWS
     */
    @WebEndpoint(name = "BBDETSISWS")
    public BBDETSISWS getBBDETSISWS(WebServiceFeature... features) {
        return super.getPort(new QName("http://kaysis.gov.tr/", "BBDETSISWS"), BBDETSISWS.class, features);
    }

    /**
     * 
     * @return
     *     returns BBDETSISWS
     */
    @WebEndpoint(name = "BBDETSISWS1")
    public BBDETSISWS getBBDETSISWS1() {
        return super.getPort(new QName("http://kaysis.gov.tr/", "BBDETSISWS1"), BBDETSISWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BBDETSISWS
     */
    @WebEndpoint(name = "BBDETSISWS1")
    public BBDETSISWS getBBDETSISWS1(WebServiceFeature... features) {
        return super.getPort(new QName("http://kaysis.gov.tr/", "BBDETSISWS1"), BBDETSISWS.class, features);
    }

    /**
     * 
     * @return
     *     returns DETSISServisHttpGet
     */
    @WebEndpoint(name = "DETSISServisHttpGet")
    public DETSISServisHttpGet getDETSISServisHttpGet() {
        return super.getPort(new QName("http://kaysis.gov.tr/", "DETSISServisHttpGet"), DETSISServisHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DETSISServisHttpGet
     */
    @WebEndpoint(name = "DETSISServisHttpGet")
    public DETSISServisHttpGet getDETSISServisHttpGet(WebServiceFeature... features) {
        return super.getPort(new QName("http://kaysis.gov.tr/", "DETSISServisHttpGet"), DETSISServisHttpGet.class, features);
    }

    /**
     * 
     * @return
     *     returns DETSISServisHttpPost
     */
    @WebEndpoint(name = "DETSISServisHttpPost")
    public DETSISServisHttpPost getDETSISServisHttpPost() {
        return super.getPort(new QName("http://kaysis.gov.tr/", "DETSISServisHttpPost"), DETSISServisHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DETSISServisHttpPost
     */
    @WebEndpoint(name = "DETSISServisHttpPost")
    public DETSISServisHttpPost getDETSISServisHttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("http://kaysis.gov.tr/", "DETSISServisHttpPost"), DETSISServisHttpPost.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DETSISSERVIS_EXCEPTION!= null) {
            throw DETSISSERVIS_EXCEPTION;
        }
        return DETSISSERVIS_WSDL_LOCATION;
    }

}
